/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/movement-theme.ts
 * Command: astryx theme build src/theme/movement-theme.ts
 * Generated: 2026-07-22T18:15:06.744Z
 */

/// <reference path="./democracy-is-dead.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const democracyIsDeadTheme: DefinedTheme;
