/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/movement-theme.ts
 * Command: astryx theme build src/theme/movement-theme.ts
 * Generated: 2026-07-22T18:15:06.743Z
 */

// Generated by astryx theme build
export {};

declare module '@astryxdesign/core/Badge' {
  interface BadgeVariantMap {
    'gray': true;
  }
}
